### ISSUE TITLE
运行后报tidevice.exceptions.MuxError: Launch failed

### ISSUE THREAD

**Issue by seminchen** [bytedance/Fastbot_iOS#71]
[I 211218 18:56:59 _device:810] CFBundleExecutable: FastbotRunner-Runner
[I 211218 18:56:59 _device:841] AppContainer: /private/var/mobile/Containers/Data/Application/F0D52D5C-9885-49F5
[E 211218 18:56:59 _device:878] Launch failed: NSError(CODE:2 DOMAIN:com.apple.dt.deviceprocesscontrolservice INFO:{'NSLocalizedDescription': 'Request to launch '
                               'bytedance.FastbotRunner123.xctrunner failed.',
     'NSLocalizedFailureReason': 'The operation couldn’t be completed. (null) : '
                                 'Failed to launch process with bundle identifier '
                                 "'bytedance.FastbotRunner123.xctrunner'.",
     'NSUnderlyingError': NSError(CODE:1 DOMAIN:FBSOpenApplicationErrorDomain INFO:{'BSErrorCodeDescription': 'Unspecified', 'NSLocalizedFailureReason': '(null)'})})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramFiles\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramFiles\Python\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "D:\ProgramFiles\Python\lib\site-packages\tidevice\__main__.py", line 742, in main
    actions[args.subparser](args)
  File "D:\ProgramFiles\Python\lib\site-packages\tidevice\__main__.py", line 237, in cmd_xctest
    d.xctest(args.bundle_id,
  File "D:\ProgramFiles\Python\lib\site-packages\tidevice\_device.py", line 1036, in xctest
    pid = self._launch_app_runner(bundle_id, session_identifier,
  File "D:\ProgramFiles\Python\lib\site-packages\tidevice\_device.py", line 879, in _launch_app_runner
    raise MuxError("Launch failed")
tidevice.exceptions.MuxError: Launch failed

**Comment by geron-cn** [comment]
可以先试下直接 xcodebuild 命令是否可正常运行呢， 先排除下是否是 runner 引起的问题

**Comment by seminchen** [comment]
Submit warehouse error
